$id: "https://schemata.nostr.watch/note/tag/t"
$schema: "http://json-schema.org/draft-07/schema#"
allOf:
  - $ref: "@/tag.yaml"
  - type: array
    minItems: 2
    items:
      - const: "t"
      - type: string
    additionalItems: true